config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :employee

  resources :department
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord

	has_many :employees

	validates :name, presence: true

end

app/models/employee.rb
class Employee < ApplicationRecord

	belongs_to :department

	validates :name,
		:company,
		:summary,
		:role,
		:department_id,
		:admission_date,
		:description,
		presence: true
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController

	def new
		@department = Department.new
	end

	def create
		@department = Department.new(required_params)
		if @department.save
			redirect_to @department
		else
			render :new
		end
	end

	def show
		@department = Department.find(params[:id])
	end

	def required_params
		attributes = params.require(:department)
		{
			name: attributes[:name]
		}
	end

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController

	def show
		@employee = Employee.find(params[:id])
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(require_params(params))
		if @employee.save
			redirect_to employee_path(@employee)
		else
			render :new
		end
	end

	def edit
		@employee = Employee.find(params[:id])
		# @employee[:admission_date] = date_validator(@employee[:admission_date])
	end

	def update
		@employee = Employee.find(params[:id])
		if @employee.update(require_params(params))
			redirect_to employee_path(@employee)
		else
			render :edit
		end
	end

	def require_params(params)
		data = params.require(:employee)
		data[:admission_date] = date_validator(data[:admission_date])
		data.symbolize_keys
	end

	def date_validator(date_field)
		begin
			Date.parse(date_field)
		rescue
			nil
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@employees = Employee.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/department/_form.html.erb
<% action = params[:action] == 'new' || params[:action] == 'create' ? 'create' : 'update' %>

<%= form_for @department, url: {action: action} do |f| %>
  <%= f.label :name, 'Name: ' %>
  	<%= f.text_field :name %> <br />
  <%= f.submit action.camelize %>
<% end %>

app/views/department/new.html.erb
<h1> Departments Registration </h1>

<% if @department.errors.full_messages.present? %>
  <p><strong> You need to fill in the fields !</strong></p>
  <% @department.errors.full_messages.each do |message| %>
   <p> <%= message %> </p>
  <% end %>
<% end%>

<%= render partial: 'form' %>

app/views/department/show.html.erb
<h2> Department Information </h2>
<div class="department-name">
	<label> Name: </label>
	<%= @department.name %>
</div>

app/views/employee/_form.html.erb
<% action = params[:action] == 'new' || params[:action] == 'create' ? 'create' : 'update' %>

<%= form_for @employee, url: {action: action} do |f| %>
  <%= f.label :name, 'Name: ' %>
  	<%= f.text_field :name %> <br />
  <%= f.label :company, 'Company: ' %>
		<%= f.text_field :company %> <br />
  <%= f.label :summary, 'Summary: ' %>
		<%= f.text_field :summary %> <br />
  <%= f.label :role, 'Role: ' %>
		<%= f.text_field :role %> <br />
  <%= f.label :department_id, 'Department: ' %>
    <%= f.collection_select(:department_id, Department.all, :id, :name) %> <br />
  <%= f.label :admission_date, 'Admission Date: ' %>
		<%= f.text_field :admission_date, placeholder: "dd/mm/yyy" %> <br />
  <%= f.label :description, 'Description: ' %>
		<%= f.text_field :description %> <br />
  <%= f.submit action.camelize %>
<% end %>

app/views/employee/edit.html.erb
<h1> Employee Editing </h1>

<% if @employee.errors.full_messages.present? %>
  <p><strong> You need to fill in the fields !</strong></p>
  <% @employee.errors.full_messages.each do |message| %>
   <p> <%= message %> </p>
  <% end %>
<% end%>

<%= render partial: 'form' %>

app/views/employee/new.html.erb
<h2> Employee Registration </h2>

<% if @employee.errors.full_messages.present? %>
  <p><strong> You need to fill in the fields !</strong></p>
  <% @employee.errors.full_messages.each do |message| %>
   <p> <%= message %> </p>
  <% end %>
<% end%>

<%= render partial: 'form' %>

app/views/employee/show.html.erb
<h2> Employee Information </h2>
<div class="employee-name">
	<label> Name: </label>
	<%= @employee.name %>
</div>
<div class="employee-summary">
	<label> Summary: </label>
	<%= @employee.summary %>
</div>
<div class="employee-admission">
	<label> Admission Date: </label>
	<%= @employee.admission_date.strftime("%d/%m/%Y") %>
</div>
<div class="employee-role">
	<label> Role: </label>
	<%= @employee.role %>
</div>
<div class="employee-department">
	<label> Department: </label>
	<%= @employee.department.name %>
</div>
<div class="employee-company">
	<label> Company: </label>
	<%= @employee.company %>
</div>
<div class="employee-description">
	<label> Description: </label>
	<%= @employee.description %>
</div>

<%= link_to 'Update Employee', edit_employee_path(@employee) %>
<%= link_to 'Back', root_path %>

app/views/home/index.html.erb
<h1> People Management System </h1>

<h2> Employees </h2>
<div class="admin-menu">
	<%= link_to 'Register Departments', new_department_path %>
</div>
<div class="employee-menu">
	<%= link_to 'Add Employee', new_employee_path %>
</div>
<div class="employee-group">
	<table style="width: 50%; text-align: center;">
		<tr>
			<th><strong> Name </strong></th>
			<th><strong> Role </strong></th>
			<th><strong> Department </strong></th>
		</tr>
		<% @employees.each do |employee| %>
			<tr onclick="location.href='<%= employee_path(employee) %>'">
				<td> <%= employee.name %> </td>
				<td> <%= employee.role %> </td>
				<td> <%= employee.department.name %> </td>
			</tr>
		<% end %>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>